#!/bin/bash
# author: Joe Benjamin
# uses the ask cli to generate a token to be used with the ask-sdk-local-debug package
# saves the token in your .zshrc file, this assume you already have a line like below
# script assumes you have the line like - export ASK_ACCESS_TOKEN="something"
# the line is what the script uses to replace the value each time it gets a new token
# must configure ask cli for this to work
# The ask configure command helps you configure the credentials that ASK CLI uses to authenticate you to Amazon developer services and Amazon Web Services (AWS)

echo $(ask util generate-lwa-tokens --scopes alexa::ask:skills:debug) \
| sed -E 's/.*"access_token": "(.*?)", "refresh_token".*/\1/' \
| xargs -I {} sed -E -i 's/(ASK_ACCESS_TOKEN)=".*"/\1="{}"/' ~/.zshrc

