#!/bin/bash

skill_name=$1

invocation_name=$(echo $skill_name | sed "s/_/ /g")

[[ -z "$skill_name" ]] && echo "missing param skill_name" && exit 1

sed -i "s/typescript_node_boilerplate/$skill_name/" ./skill/skill-package/skill.json ./skill/.vimspector.json ./skill/lambda/package.json
sed -i "s/typescript\snode\sboilerplate/$invocation_name/" ./skill/skill-package/interactionModels/custom/en-US.json

pushd ./skill/lambda
npm i
popd
